---
- name: Playbook
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: OS upgrade
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        autoclean: true
        autoremove: true
...